[package]
name = "bitty-observability-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Bitty observability core - shared implementation"

[dependencies]
bitty-observability-api = { path = "../bitty-observability-api", version = "0.0.1" }

[lints]
workspace = true
