[package]
name = "bitty-observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Bitty observability - metrics, tracing, and telemetry"

[dependencies]
bitty-observability-api = { path = "../bitty-observability-api" }
bitty-observability-core = { path = "../bitty-observability-core" }

[features]
default = []

[lints]
workspace = true
